apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fraud-detection-feast.serviceAccountName" . }}
  labels:
    {{- include "fraud-detection-feast.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
